// Import Icons
import 'bootstrap-icons/font/bootstrap-icons.css';

// Import Bootstrap
import 'bootstrap/dist/css/bootstrap.css';

// Import GLightbox
import 'glightbox/dist/css/glightbox.css';
import TopBar from './components/TopBar';
import Header from './components/Header';
import type { Metadata } from "next";
import { Playfair_Display, Geist, Geist_Mono, Anek_Latin } from "next/font/google";
import "./globals.css";
import BackToTop from './components/BackToTopBtn';
import Footer from './sections/Footer';
import WhatsappButton from './components/WhatsappButton';

const playfair = Playfair_Display({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '600', '700', '800', '900'],
  variable: '--font-playfair-display',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dr Glauber Queiroz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={playfair.className}>
        <TopBar />
        <Header />
        {children}
        <Footer />
        <BackToTop />
        <WhatsappButton />
      </body>
    </html>
  );
}
